language: node_js
node_js:
- '6.9'
after_success:
- npm run coverage
deploy:
  provider: npm
  email: opensource@eze.tech
  api_key:
    secure: fpVSS8pyWRcja9/+xzdIPNNt7WEEfKeqtZv2Xyk8GoW+W9Wbh1oSWLqFpsoMKPEdretjeZ032TGZnrkG/sX5rHhdCDYfMqy3p7E9pAGlspoiqQhccB9Z101pAcmqgwbx5l+FfD3j2RRDv/ew4qh9PSkuK8s0C+ikTPwtrS1+xO5PmuQW8Zd8v+MVENwuqT1biEWQZaLtWkoJp/tmFZHOoO49xbYCqhzWXnTZkUBk4dZva47iZ8KQqQBnBJHXSU77YJ72ZwhVKS8SWzg3Nm2zSN4q8D9YONEzfuvsAngXOGn41fypCNSWJ0EseqWygTqK3cp6R+zPLTkXcQhMj6Xch876LhpL1YOxjjFTjzLg3gvxiG4Uqn0BcYEDtULoIxbCGJ+7alGFEnST7wBgbKCpVhQ72mLH6V8alANlZZxqbMCD50YJ1uyHSHWyG1JqFePEC9/IvZaoD55Vxmaem77XToD4iDUdxS3vdAOtilvJo1yg7DeSvkbKSWv1FmUUIwyDWZkbv1fJAeEF/CUwZcuoCLuatLZCmHb4AxXgt36fPtlqn/ctcBTCkY7N3czSs9vDFF8QibuaAbMhg0t1xHNTW/Xhc/Q2IXYE+wUyPiy+imWyVHplpB5wAykXWdd6Q3zGxgSSCLCiQfRMudJu70GUtR+QBFfmOFS+0jXei7xco3I=
  on:
    tags: true
    repo: ezetech/react-multi-level-menu-component
